global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:

  - job_name: "web-a"
    scrape_interval: 8s
    static_configs:
      - targets: ['84.201.129.152:9100', '84.201.129.152:4040']

  - job_name: "web-b"
    scrape_interval: 8s
    static_configs:
      - targets: ['89.169.167.53:9100', '89.169.167.53:4040']

  - job_name: "prometheus-pc"
    scrape_interval: 5s
    static_configs:
      - targets: ['158.160.56.184:9090', '158.160.56.184:9100']