---

- name: Update and upgrade packages on remote machines

  hosts: all

  become: yes  # Используйте sudo

  tasks:

    - name: Update the apt package index

      apt:

        update_cache: yes

 

    - name: Upgrade all packages to the latest version

      apt:

        upgrade: dist

...